-- EL UNSIGNED LIMITA EL VALOR A POSITIVO
-- EL UNIQUE LIMITA EL VALOR A UNICO

CREATE TABLE clients (
client_id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(100),
email VARCHAR(100) UNIQUE,
phone_number VARCHAR(100) NOT NULL,

CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

MODIFIED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP 
ON UPDATE CURRENT_TIMESTAMP
);



-- comandos de utilidad

SELECT CURRENT_TIMESTAMP;

SHOW TABLES;
DESC clients;

DROP TABLE clients;


CREATE TABLE clients (
client_id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(100),
email VARCHAR(100) NOT NULL UNIQUE,
phone_number VARCHAR(100) NOT NULL,

CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

MODIFIED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP 
ON UPDATE CURRENT_TIMESTAMP
);