
-- juan compra una coca cola
-- juan compra dos doritos 
-- lucia compra un chocholate
-- lucia compra una coca cola




CLIENTS

1. juan
2. lucia

PRODUCTS

1. coca cola
2. doritos
3. chocholate


BILLS

-- [ESTO NO:]JUAN PAGO POR UNA COCA COLA , DOS DORITOS 

1. [CLIENT:1] DATE: 2025-09-02
2. [CLIENT:2] DATE: 2025-09-02


BILL_ITEMS

1.[BILL:1] [PRODUCT:1] QUANTITY: 1
2.[BILL:1] [PRODUCT:2] QUANTITY: 2
3.[BILL:2] [PRODUCT:1] QUANTITY: 1
4.[BILL:2] [PRODUCT:3] QUANTITY: 1


-- REALACIONES

1:1 
-- ES UNA RELACION QUE UNA TUPLA RELACIONADA CON UNA 
-- SOLA TUPLA DE LA TABLA 
-- UN PASAPORTE LE PERTENECE A UNA SOLA PERSONA

1:N
-- UNA TUPLA RELACIONADA CON VARIAS TUPLAS DE LA TABLA
-- UN CLIENTE PUEDE ESTAR EN MUCHOS BILLS 

N:M

-- UNA TUPLA RELACIONADA CON VARIAS TUPLAS DE LA TABLA
